config/routes.rb
Movieposter::Application.routes.draw do

  root :to => 'main#index'
  get "/main/results" => "main#results"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  require 'will_paginate/array'
  include Movie::MovieFinder
  include Album::AlbumFinder

  def index

  end

  def results
    query_string = params[:submit_type]
    if query_string == "movie"
      movie(params[:search])
    else
      album(params[:search])
    end

  end

  def movie(query)
    if !query.empty?
      conf = image_config_settings
      results = movie_search(query)
      @results = removed_nil_images(results).paginate(:page => params[:page], :per_page => 1)
      @image = conf["base_url"] + conf["size"]
    else
      redirect_to root_path
    end
  end

  def album(query)
    if !query.empty?
      results = album_search(params[:search]) 
      @results = (results).paginate(:page => params[:page], :per_page => 1)
      render "album/album_results"
    else
      redirect_to root_path
    end
  end

private

# delete a nil image record:
  def removed_nil_images(results)
    results.delete_if {|x| x["image"] == nil}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper

  def date_format(date)
    date.to_date.strftime("#{date.to_date.day.ordinalize} %B %Y")
  end

end

app/views/album/album_results.html.erb
<div class="container">
  <div class="row">
    <div class="span8 offset2">
      <% if @results.empty? %>
        <h1 class="resultTitle">sorry we can't find anything for that movie.</h1>
        <%= link_to "Back To Search", root_path, :class => 'backButton' %>
      <% end %>
       
      <% @results.each do |a| %>
        <h1 class="resultTitle"><%= a["collectionName"] %></h3>
        <div class="thumbnail">
          <img src=<%= a["artworkUrl100"].gsub("100x100-75.jpg", "400x400-75.jpg") %>>
          <%= will_paginate @results, :previous_label => "&laquo; Prev", :next_label => "Next &raquo;", :inner_window => 1, :outer_window => 1, :renderer => BootstrapPagination::Rails %>
        </div>
        <%= link_to "Back To Search", root_path, :class => 'backButton' %>
      <% end %>
   </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <title>Movieposter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= render 'shared/footer' %>

</body>
</html>

app/views/main/index.html.erb
<div class="container margin50">
  <div class="row">
    <div class="span6 offset3 cf formBackground">
      <h1>CoverArt Finder</h1>
      <%= form_tag main_results_path, :method => "get" do %>
        <%= text_field_tag 'search', nil, :placeholder => 'Enter Film Name or Album Name Here.....'%>
        <div class="labelTag">
          <%= label_tag "Movie" %>
          <%= radio_button_tag 'submit_type', 'movie', true %>
          <%= label_tag "Album" %>
          <%= radio_button_tag 'submit_type', 'album' %>
        </div>
        <%= submit_tag "search", :id => 'submitForm' %>
      <% end %>
    </div>
  </div>
</div>

app/views/main/results.html.erb
<div class="container margin50">
  <div class="row">
    <div class="span8 offset2">
      <% if @results.empty? %>
        <h1 class="resultTitle">sorry we can't find anything for that movie.</h1>
        <%= link_to "Back To Search", root_path, :class => 'backButton' %>
      <% end %>

      <% @results.each do |r| %>
        <h1 class="resultTitle"><%= r["title"] %></h1>
        <% if r["release_date"] %>
          <h3 class="releaseDate">Released: <%= date_format(r["release_date"]) %></h3>
        <% end %>

        <div class="thumbnail">
        <img class="poster" src=<%= @image + r["image"] %>/>
        <%= will_paginate @results, :previous_label => "&laquo; Prev", :next_label => "Next &raquo;", :inner_window => 1, :outer_window => 1, :renderer => BootstrapPagination::Rails %>
        </div>
        <%= link_to "Back To Search", root_path, :class => 'backButton' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
<div class="container">
  <div class="row">
    <div class="span12">
      <ul>
        <li><a href= "http://www.themoviedb.org/">Powered by TMDb</a> & <a href= "http://www.apple.com/uk/itunes/">itunes</a></li>
      </ul>
    </div>
  </div>
</div>
</footer>